In [1]:
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
# uniform 분포 주사위 분포
np.random.uniform(low=0.0, high=1.0)

0.35790732116393964

## Generate Dataset

In [3]:
# x = np.random.uniform(low=0.0, high=1.0, size=100)
# print(x.shape)

# x[:10]

In [4]:
x1 = np.random.uniform(low=0.0, high=1.0, size=100)
print(x1.shape)

x1[:10]

(100,)


array([ 0.42787751,  0.97010189,  0.04801786,  0.50268836,  0.08229988,
        0.1386973 ,  0.34997605,  0.87052722,  0.54996296,  0.98108602])

In [5]:
x2 = np.random.uniform(low=0.0, high=1.0, size=100)
print(x2.shape)

x2[:10]

(100,)


array([ 0.11821357,  0.53303083,  0.95315903,  0.31861475,  0.85769167,
        0.60635732,  0.36737935,  0.38095924,  0.65981863,  0.8156721 ])

In [8]:
y = x1 * 0.3 + x2 * 0.5 + 0.1 + (np.random.uniform(low=0.0, high=1.0, size=100) * 0.01) # 0.1 bias
print(y.shape)

y[:10]

(100,)


array([ 0.29284975,  0.66494549,  0.60077652,  0.41074678,  0.56057078,
        0.45066519,  0.39203781,  0.55486563,  0.59856969,  0.80436935])

In [7]:
# plt.scatter(x, y)

## y = wx

## Case 1 - Random Search

범위가 한정적이고 느리다.

In [9]:
# num_epoch = 100

# best_error = np.inf
# best_w = None

# for epoch in range(num_epoch):
#     w = np.random.uniform(low=0.0, high=1.0)
#     y_predict = x * w
    
#     error = np.abs(y_predict - y).mean()
    
#     if error < best_error:
#         best_error = error
#         best_w = w
        
#         print("{0:2} w = {1:.5f} error = {2:.5f}".format(epoch, w, error))
    
# print("----" * 10)
# print("{0:2} w = {1:.5f} error = {2:.5f}".format(epoch, best_w, best_error))

In [24]:
num_epoch = 10000

best_error = np.inf
best_w1 = None
best_w2 = None
best_b = None

for epoch in range(num_epoch):
    w1 = np.random.uniform(low=0.0, high=1.0)
    w2 = np.random.uniform(low=0.0, high=1.0)
    b = np.random.uniform(low=0.0, high=1.0)
    
    y_predict = x1 * w1 + x2 * w2 + b
    
    error = np.abs(y_predict - y).mean()
    
    if error < best_error:
        best_error = error
        best_w1 = w1
        best_w2 = w2
        best_b = b
        
        print("{0:2} w1 = {1:.5f}, w2 = {2:.5f}, b = {3:.5f} error = {4:.5f}".format(epoch, w1, w2, b, error))
    
print("----" * 10)
print("{0:2} w1 = {1:.5f}, w2 = {2:.5f}, b = {3:.5f} error = {4:.5f}".format(epoch, best_w1, best_w2, best_b, best_error))

 0 w1 = 0.26351, w2 = 0.88314, b = 0.68613 error = 0.75437
 1 w1 = 0.12299, w2 = 0.48308, b = 0.69306 error = 0.48742
 2 w1 = 0.86456, w2 = 0.09342, b = 0.04478 error = 0.17809
 9 w1 = 0.18736, w2 = 0.94329, b = 0.05042 error = 0.13755
21 w1 = 0.19784, w2 = 0.92475, b = 0.05346 error = 0.13340
38 w1 = 0.16158, w2 = 0.37666, b = 0.30375 error = 0.06974
44 w1 = 0.29272, w2 = 0.31309, b = 0.15966 error = 0.05316
64 w1 = 0.37179, w2 = 0.48826, b = 0.04024 error = 0.03395
999 w1 = 0.23030, w2 = 0.59010, b = 0.07568 error = 0.03230
1235 w1 = 0.23395, w2 = 0.45086, b = 0.18357 error = 0.02489
1268 w1 = 0.26902, w2 = 0.55864, b = 0.08078 error = 0.01832
1656 w1 = 0.28167, w2 = 0.47395, b = 0.13523 error = 0.00953
----------------------------------------
9999 w1 = 0.28167, w2 = 0.47395, b = 0.13523 error = 0.00953


## Case 2 - h-step Search

In [137]:
num_epoch = 1000

w = np.random.uniform(low=0.0, high=1.0)
h = 0.01

for epoch in range(num_epoch):
    y_predict = x * w
    current_error = np.abs(y_predict - y).mean()
    
    y_predict = x * (w + h)
    h_plus_error = np.abs(y_predict - y).mean()
    if h_plus_error < current_error:
        w = w + h
        continue
        
    y_predict = x * (w - h)
    h_minus_error = np.abs(y_predict - y).mean()
    if h_minus_error < current_error:
        w = w - h
        continue
        
    break
    
print("{0:2} w = {1:.5f} error = {2:.5f}".format(epoch, w, current_error))

40 w = 0.30975 error = 0.00332


- w1, w2 집에서 짜보기

## Case 3 - Gradient Descent

In [37]:
# num_epoch = 100

# # w = np.random.uniform(low=0.0, high=1.0)
# w = -9999

# for epoch in range(num_epoch):
#     y_predict = x * w
    
#     error = np.abs(y_predict - y).mean()
#     if error < 0.005:
#         break
        
#     w = w - (y_predict - y).mean()
    
#     print("{0:2} w = {1:.5f}, error = {2:.5f}".format(epoch, w, error))

# print("-----" * 10)
# print("{0:2} w = {1:.5f}, error = {2:.5f}".format(epoch, w, error))

In [57]:
num_epoch = 1000
learning_rate = 1.2

# w1 = np.random.uniform(low=0.0, high=1.0)
# w2 = np.random.uniform(low=0.0, high=1.0)
# b = np.random.uniform(low=0.0, high=1.0)
w1 = -9999
w2 = -9999
b = -9999

for epoch in range(num_epoch):
    y_predict = x1 * w1 + x2 * w2 + b
#     y_predict = x1 * w1 + x2 * w2 + x3(1) * b
    
    error = np.abs(y_predict - y).mean()
    if error < 0.005:
        break
        
    w1 = w1 - learning_rate * ((y_predict - y) * x1).mean()
    w2 = w2 - learning_rate * ((y_predict - y) * x2).mean()
    b = b - learning_rate * ((y_predict - y)).mean()
    
    if epoch % 10 == 0:
        print("{0:2} w1 = {1:.5f}, w2 = {2:.5f}, b = {3:.5f}, error = {4:.5f}".format(epoch, w1, w2, b, error))

print("-----" * 10)
print("{0:2} w1 = {1:.5f}, w2 = {2:.5f}, b = {3:.5f}, error = {4:.5f}".format(epoch, w1, w2, b, error))

 0 w1 = 3538.59639, w2 = 2951.13520, b = 14248.35511, error = 20206.12926
10 w1 = -88.91716, w2 = -505.27590, b = 4065.96122, error = 4224.84926
20 w1 = -484.83158, w2 = -756.27151, b = 1456.03498, error = 870.80876
30 w1 = -364.15864, w2 = -531.12343, b = 646.06739, error = 224.70759
40 w1 = -224.57811, w2 = -323.75296, b = 328.58250, error = 101.27193
50 w1 = -130.91473, w2 = -188.62607, b = 178.50774, error = 55.65032
60 w1 = -74.87400, w2 = -108.04314, b = 99.69510, error = 31.38389
70 w1 = -42.50557, w2 = -61.41145, b = 56.29891, error = 17.78398
80 w1 = -24.02659, w2 = -34.72718, b = 31.94256, error = 10.09246
90 w1 = -13.51701, w2 = -19.52407, b = 18.17111, error = 5.73097
100 w1 = -7.54673, w2 = -10.87749, b = 10.36262, error = 3.25504
110 w1 = -4.15608, w2 = -5.96346, b = 5.93044, error = 1.84890
120 w1 = -2.23051, w2 = -3.17161, b = 3.41368, error = 1.05027
130 w1 = -1.13693, w2 = -1.58567, b = 1.98434, error = 0.59666
140 w1 = -0.51584, w2 = -0.68482, b = 1.17253, error = 0.

## Boston Housing Dataset

In [58]:
from sklearn.datasets import load_boston

boston = load_boston()

In [59]:
X = boston["data"]

print(X.shape)
X[0]

(506, 13)


array([  6.32000000e-03,   1.80000000e+01,   2.31000000e+00,
         0.00000000e+00,   5.38000000e-01,   6.57500000e+00,
         6.52000000e+01,   4.09000000e+00,   1.00000000e+00,
         2.96000000e+02,   1.53000000e+01,   3.96900000e+02,
         4.98000000e+00])

In [60]:
y = boston["target"]

print(y.shape)
y[0]

(506,)


24.0

In [62]:
import pandas as pd

data = pd.DataFrame(X, columns=boston["feature_names"])
data["PRICE"] = y

print(data.shape)
data.head()

(506, 14)


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  PRICE  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [69]:
x1 = np.array(data["CRIM"])
x2 = np.array(data["ZN"])
x3 = np.array(data["INDUS"])
x4 = np.array(data["CHAS"])
x5 = np.array(data["NOX"])
x6 = np.array(data["RM"])
x7 = np.array(data["AGE"])
x8 = np.array(data["DIS"])
x9 = np.array(data["RAD"])
x10 = np.array(data["TAX"])
x11 = np.array(data["PTRATIO"])
x12 = np.array(data["B"])
x13 = np.array(data["LSTAT"])

In [119]:
num_epoch = 1000000
learning_rate = 0.000006

w1 = np.random.uniform(low=0.0, high=1.0)
w2 = np.random.uniform(low=0.0, high=1.0)
w3 = np.random.uniform(low=0.0, high=1.0)
w4 = np.random.uniform(low=0.0, high=1.0)
w5 = np.random.uniform(low=0.0, high=1.0)
w6 = np.random.uniform(low=0.0, high=1.0)
w7 = np.random.uniform(low=0.0, high=1.0)
w8 = np.random.uniform(low=0.0, high=1.0)
w9 = np.random.uniform(low=0.0, high=1.0)
w10 = np.random.uniform(low=0.0, high=1.0)
w11 = np.random.uniform(low=0.0, high=1.0)
w12 = np.random.uniform(low=0.0, high=1.0)
w13 = np.random.uniform(low=0.0, high=1.0)
b = np.random.uniform(low=0.0, high=1.0)

for epoch in range(num_epoch):
    y_predict = x1 * w1 + x2 * w2 + x3 * w3 + x4 * w4 + x5 * w5 + x6 * w6 \
                 + x7 * w7 + x8 * w8 + x9 * w9 + x10 * w10 + x11 * w11 + x12 * w12 + x13 * w13 + b
    
    error = np.abs(y_predict - y).mean()
    if error < 0.005:
        break
        
    w1 = w1 - learning_rate * ((y_predict - y) * x1).mean()
    w2 = w2 - learning_rate * ((y_predict - y) * x2).mean()
    w3 = w3 - learning_rate * ((y_predict - y) * x3).mean()
    w4 = w4 - learning_rate * ((y_predict - y) * x4).mean()
    w5 = w5 - learning_rate * ((y_predict - y) * x5).mean()
    w6 = w6 - learning_rate * ((y_predict - y) * x6).mean()
    w7 = w7 - learning_rate * ((y_predict - y) * x7).mean()
    w8 = w8 - learning_rate * ((y_predict - y) * x8).mean()
    w9 = w9 - learning_rate * ((y_predict - y) * x9).mean()
    w10 = w10 - learning_rate * ((y_predict - y) * x10).mean()
    w11 = w11 - learning_rate * ((y_predict - y) * x11).mean()
    w12 = w12 - learning_rate * ((y_predict - y) * x12).mean()
    w13 = w13 - learning_rate * ((y_predict - y) * x13).mean()
    b = b - learning_rate * ((y_predict - y)).mean()

    if epoch % 100000 == 0:
        print("{0:2} w1 = {1:.5f}, b = {2:.5f} error = {3:.5f}".format(epoch, w1, b, error))
#         print("{0:2} w1 = {1:.5f}, w2 = {2:.5f}, b = {3:.5f}, error = {4:.5f}".format(epoch, w1, w2, b, error))

print("-----" * 10)
print("{0:2} w1 = {1:.5f}, b = {2:.5f} error = {3:.5f}".format(epoch, w1, b, error))
# print("{0:2} w1 = {1:.5f}, w2 = {2:.5f}, b = {3:.5f}, error = {4:.5f}".format(epoch, w1, w2, b, error))

 0 w1 = 0.57523, b = 0.91232 error = 361.53900
100000 w1 = -0.08078, b = 1.06640 error = 4.28115
200000 w1 = -0.08650, b = 1.18141 error = 3.84138
300000 w1 = -0.08968, b = 1.27005 error = 3.58881
400000 w1 = -0.09145, b = 1.34059 error = 3.44810
500000 w1 = -0.09245, b = 1.39873 error = 3.37005
600000 w1 = -0.09301, b = 1.44842 error = 3.32757
700000 w1 = -0.09333, b = 1.49233 error = 3.30524
800000 w1 = -0.09349, b = 1.53231 error = 3.29502
900000 w1 = -0.09356, b = 1.56960 error = 3.28961
--------------------------------------------------
999999 w1 = -0.09358, b = 1.60505 error = 3.28648


In [165]:
W = np.random.uniform(low=0.0, high=1.0, size=13)

W.append(np.array([1]))
W = np.array(W)
W

array([[ 0.4603878 ],
       [ 0.52447713],
       [ 0.49473627],
       [ 0.9605878 ],
       [ 0.00257041],
       [ 0.39155562],
       [ 0.69777731],
       [ 0.52188575],
       [ 0.25561006],
       [ 0.71467278],
       [ 0.06399961],
       [ 0.91204529],
       [ 0.42795125],
       [ 1.        ]])

In [166]:
columns = ["CRIM", "ZN", "INDUS", "CHAS", "NOX", "RM", "AGE", "DIS", "RAD", "TAX", "PTRATIO", "B", "LSTAT"]
X = []

for c in columns:
    X.append(np.array(data[c]))

X.append(np.random.uniform(low=0.0, high=1.0, size=506))
X = np.array(X)
X

array([[  6.32000000e-03,   2.73100000e-02,   2.72900000e-02, ...,
          6.07600000e-02,   1.09590000e-01,   4.74100000e-02],
       [  1.80000000e+01,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  2.31000000e+00,   7.07000000e+00,   7.07000000e+00, ...,
          1.19300000e+01,   1.19300000e+01,   1.19300000e+01],
       ..., 
       [  3.96900000e+02,   3.96900000e+02,   3.92830000e+02, ...,
          3.96900000e+02,   3.93450000e+02,   3.96900000e+02],
       [  4.98000000e+00,   9.14000000e+00,   4.03000000e+00, ...,
          5.64000000e+00,   6.48000000e+00,   7.88000000e+00],
       [  2.35630038e-01,   6.64843379e-01,   7.30365700e-01, ...,
          3.03542339e-01,   3.74617648e-01,   8.05224785e-01]])

In [167]:
num_epoch = 10000
learning_rate = 0.000006

for epoch in range(num_epoch):
    y_predict = W * X
    
    error = np.abs(y_predict - y).mean()
    if error < 0.005:
        break
        
    W = W - learning_rate * ((y_predict - y) * X).mean()

    if epoch % 1000 == 0:
        print("{0:2} error = {1:.5f}".format(epoch, error))
#         print("{0:2} w1 = {1:.5f}, w2 = {2:.5f}, b = {3:.5f}, error = {4:.5f}".format(epoch, w1, w2, b, error))

print("-----" * 10)
print("{0:2} error = {1:.5f}".format(epoch, error))
# print("{0:2} w1 = {1:.5f}, w2 = {2:.5f}, b = {3:.5f}, error = {4:.5f}".format(epoch, w1, w2, b, error))

 0 error = 59.01437
1000 error = 26.77496
2000 error = 26.77496
3000 error = 26.77496
4000 error = 26.77496
5000 error = 26.77496
6000 error = 26.77496
7000 error = 26.77496
8000 error = 26.77496
9000 error = 26.77496
--------------------------------------------------
9999 error = 26.77496
