In [23]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Load Dataset

In [3]:
from keras.datasets import mnist

((X_train, y_train), (X_test, y_test)) = mnist.load_data()

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

Using TensorFlow backend.


(60000, 28, 28) (60000,)
(10000, 28, 28) (10000,)


## Preprocessing

In [16]:
X_train = X_train.reshape(60000, 28 * 28)
X_test = X_test.reshape(10000, 28 * 28)

print(X_train.shape, X_test.shape)

(60000, 784) (10000, 784)


In [17]:
from keras.utils import to_categorical

y_train_hot = to_categorical(y_train)
y_test_hot = to_categorical(y_test)

print(y_train_hot.shape, y_test_hot.shape)

print("Label = {0}".format(y_train[0:3]))
print(y_train_hot[0:3])

print("Label = {0}".format(y_test[0:3]))
print(y_test_hot[0:3])

(60000, 10) (10000, 10)
Label = [5 0 4]
[[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]]
Label = [7 2 1]
[[ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]]


## Build a model

### Single Layer

In [39]:
from keras.models import Sequential
from keras.layers import Dense
from keras.initializers import RandomUniform
from keras.optimizers import SGD

model = Sequential()
model.add(Dense(units=10, 
                kernel_initializer=RandomUniform(minval=0.0, maxval=0.001),
                activation='sigmoid', 
                input_dim=28*28))

# loss = Cross Entropy
# optimizer = Stochastic Gradient Descent (SGD)
model.compile(loss='categorical_crossentropy', optimizer=SGD(lr=0.00001), metrics=['accuracy'])

In [40]:
model.fit(X_train, y_train_hot, epochs=100)

Epoch 1/100
60000/60000 [==============================] - 4s 66us/step - loss: 2.3023 - acc: 0.2048
Epoch 2/100
60000/60000 [==============================] - 4s 65us/step - loss: 2.0228 - acc: 0.1321
Epoch 3/100
60000/60000 [==============================] - 4s 73us/step - loss: 1.0415 - acc: 0.1134
Epoch 4/100
60000/60000 [==============================] - 3s 51us/step - loss: 1.0034 - acc: 0.1182
Epoch 5/100
60000/60000 [==============================] - 3s 54us/step - loss: 0.9905 - acc: 0.1233
Epoch 6/100
60000/60000 [==============================] - 4s 73us/step - loss: 0.9835 - acc: 0.1269
Epoch 7/100
60000/60000 [==============================] - 4s 69us/step - loss: 0.9770 - acc: 0.1333
Epoch 8/100
60000/60000 [==============================] - 4s 61us/step - loss: 0.9730 - acc: 0.1397
Epoch 9/100
60000/60000 [==============================] - 3s 56us/step - loss: 0.9694 - acc: 0.1492
Epoch 10/100
60000/60000 [==============================] - 4s 71us/step - loss: 0.9669 - a

60000/60000 [==============================] - 4s 59us/step - loss: 0.2684 - acc: 0.9234
Epoch 82/100
60000/60000 [==============================] - 5s 77us/step - loss: 0.2678 - acc: 0.9231
Epoch 83/100
60000/60000 [==============================] - 4s 59us/step - loss: 0.2671 - acc: 0.9237
Epoch 84/100
60000/60000 [==============================] - 4s 62us/step - loss: 0.2683 - acc: 0.9235
Epoch 85/100
60000/60000 [==============================] - 4s 66us/step - loss: 0.2674 - acc: 0.9230
Epoch 86/100
60000/60000 [==============================] - 4s 70us/step - loss: 0.2667 - acc: 0.9235
Epoch 87/100
60000/60000 [==============================] - 4s 59us/step - loss: 0.2662 - acc: 0.9235
Epoch 88/100
60000/60000 [==============================] - 4s 64us/step - loss: 0.2670 - acc: 0.9239
Epoch 89/100
60000/60000 [==============================] - 4s 67us/step - loss: 0.2662 - acc: 0.9248
Epoch 90/100
60000/60000 [==============================] - 5s 79us/step - loss: 0.2661 - acc: 

In [41]:
y_predict = model.predict(X_test)
y_predict = np.argmax(y_predict, axis=1)

accuracy = (y_predict == y_test).mean()

print("Accuracy = {0:.5f}".format(accuracy))
pd.DataFrame({'y(actual)': y_test, 'y(predict)': y_predict}).head(15)

Accuracy = 0.91890


y(actual)  y(predict)
0           7           7
1           2           2
2           1           1
3           0           0
4           4           4
5           1           1
6           4           4
7           9           9
8           5           6
9           9           9
10          0           0
11          6           6
12          9           9
13          0           0
14          1           1

### Multi-layer

In [75]:
# sigmoid
fanin = 784
fanout = 1000

minval = -np.sqrt(6 / (fanin + fanout))
maxval = +np.sqrt(6 / (fanin + fanout))

print("{0:.5f} ~ {1:.5f}".format(minval, maxval))

-0.05799 ~ 0.05799


In [48]:
from keras.models import Sequential
from keras.layers import Dense
from keras.initializers import RandomUniform
from keras.optimizers import SGD

model = Sequential()
model.add(Dense(units=1000, 
                kernel_initializer=RandomUniform(minval=-0.058, maxval=+0.058),
                activation='sigmoid', 
                input_dim=28*28))

model.add(Dense(units=10, 
                kernel_initializer=RandomUniform(minval=-0.077, maxval=+0.077),
                activation='sigmoid'))

# loss = Cross Entropy
# optimizer = Stochastic Gradient Descent (SGD)
model.compile(loss='categorical_crossentropy', optimizer=SGD(lr=0.0001), metrics=['accuracy'])

In [49]:
model.fit(X_train, y_train_hot, epochs=10, validation_date(X_test, y_test_hot))

Epoch 1/10
60000/60000 [==============================] - 14s 238us/step - loss: 2.1540 - acc: 0.2324
Epoch 2/10
60000/60000 [==============================] - 15s 250us/step - loss: 1.8067 - acc: 0.5068
Epoch 3/10
60000/60000 [==============================] - 15s 253us/step - loss: 1.4138 - acc: 0.6842
Epoch 4/10
60000/60000 [==============================] - 14s 237us/step - loss: 1.1164 - acc: 0.7656
Epoch 5/10
60000/60000 [==============================] - 15s 246us/step - loss: 0.9287 - acc: 0.8065
Epoch 6/10
60000/60000 [==============================] - 15s 255us/step - loss: 0.8068 - acc: 0.8304
Epoch 7/10
60000/60000 [==============================] - 14s 236us/step - loss: 0.7214 - acc: 0.8464
Epoch 8/10
60000/60000 [==============================] - 15s 247us/step - loss: 0.6586 - acc: 0.8577
Epoch 9/10
60000/60000 [==============================] - 16s 259us/step - loss: 0.6105 - acc: 0.8659
Epoch 10/10
60000/60000 [==============================] - 15s 253us/step - loss: 

In [54]:
y_predict = model.predict(X_test)
y_predict = np.argmax(y_predict, axis=1)

accuracy = (y_predict == y_test).mean()

print("Accuracy = {0:.5f}".format(accuracy))
pd.DataFrame({'y(actual)': y_test, 'y(predict)': y_predict}).head(15)

Accuracy = 0.87690


y(actual)  y(predict)
0           7           7
1           2           6
2           1           1
3           0           0
4           4           4
5           1           1
6           4           4
7           9           9
8           5           2
9           9           9
10          0           0
11          6           6
12          9           9
13          0           0
14          1           1

## Keras 를 가지고 95% 이상