In [1]:
import numpy as np

In [2]:
# uniform 분포로 랜덤값을 생성
np.random.uniform(low=0.0, high=1.0)

0.07231893877254936

# Generate Dataset

In [3]:
x1 = np.random.uniform(low=0.0, high=1.0, size=100)

print(x1.shape)
x1[:10]

(100,)


array([ 0.36303337,  0.93028992,  0.36793582,  0.35930595,  0.81950208,
        0.74285439,  0.33007483,  0.41516824,  0.48994797,  0.85645599])

In [4]:
x2 = np.random.uniform(low=0.0, high=1.0, size=100)

print(x2.shape)
x2[:10]

(100,)


array([ 0.19881625,  0.23588483,  0.41872211,  0.51375363,  0.38375441,
        0.66254183,  0.31430451,  0.85816505,  0.24361595,  0.38731356])

In [5]:
y = (x1 * 0.3) + (x2 * 0.5) + 0.1 + (np.random.uniform(low=0.0, high=1.0, size=100) * 0.01)

print(y.shape)
y[:10]

(100,)


array([ 0.31773953,  0.49783231,  0.42578581,  0.47344658,  0.54487648,
        0.65932468,  0.35674002,  0.66046614,  0.37623266,  0.55868733])

In [6]:
# %matplotlib inline
# import matplotlib.pyplot as plt

# plt.scatter(x, y)

# Case 1 - Random Search

In [7]:
num_epoch = 10000

best_w1 = None
best_w2 = None
best_b = None
best_error = 999

for epoch in range(num_epoch):
    w1 = np.random.uniform(low=0.0, high=1.0)
    w2 = np.random.uniform(low=0.0, high=1.0)
    b = np.random.uniform(low=0.0, high=1.0)
    
    y_predict = (x1 * w1) + (x2 * w2) + b
    error = np.abs(y_predict - y).mean()
    
    if error < best_error:
        best_w1 = w1
        best_w2 = w2
        best_b = b
        best_error = error
        
        print("{0:2} w1 = {1:.5f}, w2 = {2:.5f}, b = {3:.5f}, error = {4:.5f}".format(epoch, w1, w2, b, error))
    
print("------------------------------------------")
print("{0:2} w1 = {1:.5f}, w2 = {2:.5f}, b = {3:.5f}, error = {4:.5f}".format(epoch, best_w1, best_w2, best_b, best_error))

 0 w1 = 0.04002, w2 = 0.77393, b = 0.11122, error = 0.09010
28 w1 = 0.27868, w2 = 0.18193, b = 0.30304, error = 0.08312
78 w1 = 0.45972, w2 = 0.32884, b = 0.10080, error = 0.05535
273 w1 = 0.21824, w2 = 0.40559, b = 0.22731, error = 0.03830
410 w1 = 0.22189, w2 = 0.50068, b = 0.13425, error = 0.02058
637 w1 = 0.32044, w2 = 0.47024, b = 0.12777, error = 0.01919
1758 w1 = 0.33996, w2 = 0.53058, b = 0.05061, error = 0.01863
2424 w1 = 0.28190, w2 = 0.50539, b = 0.11068, error = 0.00505
------------------------------------------
9999 w1 = 0.28190, w2 = 0.50539, b = 0.11068, error = 0.00505


# Case 2 - h-step Search

In [8]:
# num_epoch = 1000

# w = np.random.uniform(low=0.0, high=1.0)
# h = 0.01

# for epoch in range(num_epoch):
#     y_predict = x * w
#     current_error = np.abs(y_predict - y).mean()
    
#     y_predict = x * (w + h)
#     h_plus_error = np.abs(y_predict - y).mean()
    
#     if h_plus_error < current_error:
#         w = w + h
#         continue
    
#     y_predict = x * (w - h)
#     h_minus_error = np.abs(y_predict - y).mean()
    
#     if h_minus_error < current_error:
#         w = w - h
#         continue
    
#     break

# print("{0} w = {1:.5f} error = {2:.5f}".format(epoch, w, current_error))        

# Case 3 - Gradient Desent

In [9]:
num_epoch = 1000
learning_rate = 1.2

w1 = np.random.uniform(low=-9999.0, high=9999.0)
w2 = np.random.uniform(low=-9999.0, high=9999.0)
b = np.random.uniform(low=-9999.0, high=9999.0)

for epoch in range(num_epoch):
    y_predict = (x1 * w1) + (x2 * w2) + b
    
    error = np.abs(y_predict - y).mean()
    if error < 0.005:
        break
    
    w1 = w1 - learning_rate * ((y_predict - y) * x1).mean()
    w2 = w2 - learning_rate * ((y_predict - y) * x2).mean()
    b = b - learning_rate * (y_predict - y).mean()
    
    if epoch % 10 == 0:
        print("{0:2} w1 = {1:.5f}, w2 = {2:.5f}, b = {3:.5f}, error = {4:.5f}".format(epoch, w1, w2, b, error))
    
print("------------------------------------------")
print("{0:2} w1 = {1:.5f}, w2 = {2:.5f}, b = {3:.5f}, error = {4:.5f}".format(epoch, w1, w2, b, error))

 0 w1 = 10209.71444, w2 = -2975.73552, b = 1323.16387, error = 6188.08814
10 w1 = 3748.95055, w2 = -1025.34971, b = -308.14404, error = 1517.44629
20 w1 = 1460.12466, w2 = -270.30549, b = -385.49317, error = 443.03360
30 w1 = 599.41515, w2 = -28.32409, b = -251.85839, error = 160.81848
40 w1 = 257.92977, w2 = 30.02795, b = -142.93901, error = 68.44039
50 w1 = 115.72946, w2 = 32.94931, b = -77.23325, error = 31.64337
60 w1 = 53.87316, w2 = 23.82632, b = -40.91249, error = 15.41765
70 w1 = 25.90336, w2 = 15.04759, b = -21.47796, error = 7.70402
80 w1 = 12.82706, w2 = 8.97007, b = -11.21443, error = 3.92293
90 w1 = 6.54194, w2 = 5.24482, b = -5.82352, error = 2.02597
100 w1 = 3.45330, w2 = 3.09633, b = -2.99832, error = 1.05262
110 w1 = 1.90922, w2 = 1.89952, b = -1.51909, error = 0.54839
120 w1 = 1.12728, w2 = 1.24689, b = -0.74487, error = 0.28626
130 w1 = 0.72752, w2 = 0.89580, b = -0.33972, error = 0.14976
140 w1 = 0.52173, w2 = 0.70860, b = -0.12770, error = 0.07849
150 w1 = 0.41528,

# 숙제

- Boston Housing Dataset

In [ ]:
from sklearn.datasets import load_boston

boston = load_boston()

In [ ]:
X = boston["data"]

print(X.shape)
X[0]

In [ ]:
y = boston["target"]

print(y.shape)
y[0]

In [ ]:
import pandas as pd

data = pd.DataFrame(X, columns=boston["feature_names"])
data["PRICE"] = y

print(data.shape)
data.head()

In [ ]:
data

In [ ]:
num_epoch = 10000
learning_rate = 0.0000063 # 0.00000625

crim_w = 1
zn_w = 1
indus_w = 1
chas_w = 1
nox_w = 1
rm_w = 1
age_w = 1
dis_w = 1
rad_w = 1
tax_w = 1
ptratio_w = 1
b_w = 1
lstat_w = 1
b = 1

for epoch in range(num_epoch):
    price_predict = (crim_w * data["CRIM"]) + (zn_w * data["ZN"]) + (indus_w * data["INDUS"]) + (chas_w * data["CHAS"]) + (nox_w * data["NOX"]) + (rm_w * data["RM"]) + (age_w * data["AGE"]) + (dis_w * data["DIS"]) + (rad_w * data["RAD"]) + (tax_w * data["TAX"]) + (ptratio_w * data["PTRATIO"]) + (b_w * data["B"]) + (lstat_w * data["LSTAT"]) + b
    
    error = np.abs(price_predict - data["PRICE"]).mean()
    if error < 0.005:
        break
    
    crim_w = crim_w - learning_rate * ((price_predict - data["PRICE"]) * data["CRIM"]).mean()
    zn_w = zn_w - learning_rate * ((price_predict - data["PRICE"]) * data["ZN"]).mean()
    indus_w = indus_w - learning_rate * ((price_predict - data["PRICE"]) * data["INDUS"]).mean()
    chas_w = chas_w - learning_rate * ((price_predict - data["PRICE"]) * data["CHAS"]).mean()
    nox_w = nox_w - learning_rate * ((price_predict - data["PRICE"]) * data["NOX"]).mean()
    rm_w = rm_w - learning_rate * ((price_predict - data["PRICE"]) * data["RM"]).mean()
    age_w = age_w - learning_rate * ((price_predict - data["PRICE"]) * data["AGE"]).mean()
    dis_w = dis_w - learning_rate * ((price_predict - data["PRICE"]) * data["DIS"]).mean()
    rad_w = rad_w - learning_rate * ((price_predict - data["PRICE"]) * data["RAD"]).mean()
    tax_w = tax_w - learning_rate * ((price_predict - data["PRICE"]) * data["TAX"]).mean()
    ptratio_w = ptratio_w - learning_rate * ((price_predict - data["PRICE"]) * data["PTRATIO"]).mean()
    b_w = b_w - learning_rate * ((price_predict - data["PRICE"]) * data["B"]).mean()
    lstat_w = lstat_w - learning_rate * ((price_predict - data["PRICE"]) * data["LSTAT"]).mean()
    b = b - learning_rate * (price_predict - data["PRICE"]).mean()
    
    if epoch % 100 == 0:
#         print("[{0:2}], error = {1:.5f}, crim_w = {2:.5f}, zn_w = {3:.5f}, indus_w = {4:.5f}, chas_w = {5:.5f}, nox_w = {6:.5f}, rm_w = {7:.5f}, age_w = {8:.5f}, dis_w = {9:.5f}, rad_w = {10:.5f}, tax_w = {11:.5f}, ptratio_w = {12:.5f}, b_w = {13:.5f}, lstat_w = {14:.5f}, b = {15:.5f}".format(epoch, error, crim_w, zn_w, indus_w, chas_w, nox_w, rm_w, age_w, dis_w, rad_w, tax_w, ptratio_w, b_w, lstat_w, b))
        print("[{0:2}] error = {1:.5f}".format(epoch, error))
    
print("------------------------------------------")
print("[{0:2}] error = {1:.5f}".format(epoch, error))
# print("{0:2} w1 = {1:.5f}, w2 = {2:.5f}, b = {3:.5f}, error = {4:.5f}".format(epoch, w1, w2, b, error))

In [ ]:
print("crim_w    = {0:.5f}".format(crim_w))
print("zn_w      = {0:.5f}".format(zn_w))
print("indus_w   = {0:.5f}".format(indus_w))
print("chas_w    = {0:.5f}".format(chas_w))
print("nox_w     = {0:.5f}".format(nox_w))
print("rm_w      = {0:.5f}".format(rm_w))
print("age_w     = {0:.5f}".format(age_w))
print("dis_w     = {0:.5f}".format(dis_w))
print("rad_w     = {0:.5f}".format(rad_w))
print("tax_w     = {0:.5f}".format(tax_w))
print("ptratio_w = {0:.5f}".format(ptratio_w))
print("b_w       = {0:.5f}".format(b_w))
print("lstat_w   = {0:.5f}".format(lstat_w))
print("b         = {0:.5f}".format(b))

In [ ]:
num_epoch = 10000
learning_rate = 0.0000063 # 0.00000625

w = np.random.uniform(low=0, high=1, size=13)
b = 1

for epoch in range(num_epoch):
    price_predict = (crim_w * data["CRIM"]) + (zn_w * data["ZN"]) + (indus_w * data["INDUS"]) + (chas_w * data["CHAS"]) + (nox_w * data["NOX"]) + (rm_w * data["RM"]) + (age_w * data["AGE"]) + (dis_w * data["DIS"]) + (rad_w * data["RAD"]) + (tax_w * data["TAX"]) + (ptratio_w * data["PTRATIO"]) + (b_w * data["B"]) + (lstat_w * data["LSTAT"]) + b
    
    error = np.abs(price_predict - data["PRICE"]).mean()
    if error < 0.005:
        break
    
    crim_w = crim_w - learning_rate * ((price_predict - data["PRICE"]) * data["CRIM"]).mean()
    zn_w = zn_w - learning_rate * ((price_predict - data["PRICE"]) * data["ZN"]).mean()
    indus_w = indus_w - learning_rate * ((price_predict - data["PRICE"]) * data["INDUS"]).mean()
    chas_w = chas_w - learning_rate * ((price_predict - data["PRICE"]) * data["CHAS"]).mean()
    nox_w = nox_w - learning_rate * ((price_predict - data["PRICE"]) * data["NOX"]).mean()
    rm_w = rm_w - learning_rate * ((price_predict - data["PRICE"]) * data["RM"]).mean()
    age_w = age_w - learning_rate * ((price_predict - data["PRICE"]) * data["AGE"]).mean()
    dis_w = dis_w - learning_rate * ((price_predict - data["PRICE"]) * data["DIS"]).mean()
    rad_w = rad_w - learning_rate * ((price_predict - data["PRICE"]) * data["RAD"]).mean()
    tax_w = tax_w - learning_rate * ((price_predict - data["PRICE"]) * data["TAX"]).mean()
    ptratio_w = ptratio_w - learning_rate * ((price_predict - data["PRICE"]) * data["PTRATIO"]).mean()
    b_w = b_w - learning_rate * ((price_predict - data["PRICE"]) * data["B"]).mean()
    lstat_w = lstat_w - learning_rate * ((price_predict - data["PRICE"]) * data["LSTAT"]).mean()
    b = b - learning_rate * (price_predict - data["PRICE"]).mean()
    
    if epoch % 100 == 0:
#         print("[{0:2}], error = {1:.5f}, crim_w = {2:.5f}, zn_w = {3:.5f}, indus_w = {4:.5f}, chas_w = {5:.5f}, nox_w = {6:.5f}, rm_w = {7:.5f}, age_w = {8:.5f}, dis_w = {9:.5f}, rad_w = {10:.5f}, tax_w = {11:.5f}, ptratio_w = {12:.5f}, b_w = {13:.5f}, lstat_w = {14:.5f}, b = {15:.5f}".format(epoch, error, crim_w, zn_w, indus_w, chas_w, nox_w, rm_w, age_w, dis_w, rad_w, tax_w, ptratio_w, b_w, lstat_w, b))
        print("[{0:2}] error = {1:.5f}".format(epoch, error))
    
print("------------------------------------------")
print("[{0:2}] error = {1:.5f}".format(epoch, error))
# print("{0:2} w1 = {1:.5f}, w2 = {2:.5f}, b = {3:.5f}, error = {4:.5f}".format(epoch, w1, w2, b, error))